services:
  tomcat:
    image: tomcat:9.0-jdk21-temurin
    container_name: java-tomcat
    ports:
      - "8085:8080"
    volumes:
      - ./servlet-app/target/servlet-app-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war

  liferay:
    image: liferay/portal:7.4.3.112-ga112
    container_name: java-liferay
    ports:
      - "8086:8080"
    volumes:
      - ./portlet-app/target:/opt/liferay/deploy
    restart: unless-stopped
